import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/navbar";
import { openSans } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} mx-6 flex flex-col min-h-screen`}>
          <header>
            <Navbar />
          </header>
          <main className='flex flex-grow container mx-auto mt-10'>
            {children}
          </main>
          <footer className="m-5 items-center justify-center text-gray-700 md:flex md:items-center">
            <span className="text-sm">© 2025 <a href="https://github.com/paupni" className="cursor-pointer hover:text-gray-400 transition-all duration-300">@paupni</a> | All Rights Reserved</span>
          </footer>
          
      </body>
    </html>
  );
}
