import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
              <header>
                <Navbar />
              </header>
              <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
                {children}
              </main>
              <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
                footer
              </footer>

      </body>
    </html>
  );
}
